name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Install dependencies
        working-directory: lambda
        run: |
          pip install -r requirements.txt -t .
          zip -r ../lambda.zip .

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init

      - name: Plan Terraform
        working-directory: terraform
        run: terraform plan -var "lambda_source_code=../lambda.zip"

      - name: Apply Terraform
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve -var "lambda_source_code=../lambda.zip"
